# Site wide configuration

title: "疫情下的工人"
description: "我们搜索整理新冠肺炎疫情中工人的处境与行动"
logo: logo-120x120.jpg # 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: zh
url: 
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:year/:month/:day/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
  - "_pages"
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
